{% set version = "0.11.6" %}
{% set sha256 = "ab00bb03c4809e2330ccde8d8bb3ec29ef4f59dd43143873ddcdae39072dfce5" %}

package:
  name: ipyleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - jupyter
  run:
    - python
    - ipywidgets >=7.5.0,<8.0.0
    - traittypes >=0.2.1,<0.3.0
    - xarray >=0.10.0
    - branca >=0.3.1,<0.4.0

test:
  imports:
    - ipyleaflet

about:
  home: https://github.com/jupyter-widgets/ipyleaflet
  license: MIT
  license_file: LICENSE
  summary: A Jupyter widget for dynamic Leaflet maps
  doc_url: http://ipyleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipyleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
    - martinRenou
