{% set version = "0.7.3" %}

package:
  name: ipyleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
  sha256: 6f814b60d702dbc5d582c945c35fad52f970faed391712cf3eecc845c33fdf2c

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - jupyter
  run:
    - python
    - ipywidgets >=7.0.0,<8.0.0

test:
  imports:
    - ipyleaflet

about:
  home: https://github.com/ellisonbg/ipyleaflet
  license: MIT
  summary: A Jupyter widget for dynamic Leaflet maps

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
