{% set version = "0.17.4" %}
{% set sha256 = "70e8772fe501da05a57e84a11734bf35fdd6b7dfb556a3dbfe93b5ab6fe747ae" %}

package:
  name: ipyleaflet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipyleaflet/ipyleaflet-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - nodejs >=16
  host:
    - python >=3.7
    - pip
    - jupyter
    - jupyterlab >=3,<3.6
    - jupyter-packaging >=0.12,<1
  run:
    - python >=3.7
    - ipywidgets >=7.6.0,<9
    - traittypes >=0.2.1,<0.3.0
    - xyzservices >=2021.8.1
    - branca >=0.5.0

test:
  imports:
    - ipyleaflet
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/extension.js                             # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-leaflet/index.js                                 # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-leaflet/package.json                            # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\extension.js (exit 1)           # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-leaflet\\index.js (exit 1)               # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-leaflet\\package.json (exit 1)          # [win]

about:
  home: https://github.com/jupyter-widgets/ipyleaflet
  license: MIT
  license_file: LICENSE
  summary: A Jupyter widget for dynamic Leaflet maps
  doc_url: http://ipyleaflet.readthedocs.io
  dev_url: https://github.com/jupyter-widgets/ipyleaflet

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ellisonbg
    - jasongrout
    - martinRenou
    - davidbrochart
